[build-system]
requires = [
    "setuptools>=42",
    "setuptools-scm",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.pytest.ini_options]
addopts = "--ignore tests/example"
pytester_example_dir = "tests/example"
testpaths = [
  "tests",
]
